package com.acooldog.toolbox.algorithmkit.instruction.dsl;

public enum TestAction {
    GENERATE_STEP_FREQUENCY,
    GENERATE_GPS_TRAJECTORY,
    GENERATE_SENSOR_DATA,
    CHECK_ROOT_STATUS,
    CHECK_DEVELOPER_OPTIONS,
    CHECK_MOCK_LOCATION,
    CHECK_HOOK_FRAMEWORK,
    VALIDATE_SENSOR_CONSISTENCY,
    VALIDATE_MOTION_PATTERN,
    VALIDATE_LOCATION_DRIFT,
    WAIT_FOR_DURATION,
    SET_TEST_CONDITION,
    ASSERT_EXPECTED_RESULT,
    SIMULATE_GPS_JUMP
}
